import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Exhibition } from "@/types";

export type ExhibitionsCrudEntity = Exhibition & Record<string, unknown>;

export const exhibitionsCrudConfig: CrudModuleConfiguration<ExhibitionsCrudEntity> = {
  moduleKey: "exhibitions",
  moduleLabel: "Exhibitions",
  routePath: "/admin/exhibitions",
  entityLabel: "Exhibition",
  entityLabelPlural: "Exhibitions",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "description_en",
    "description_ar",
    "venue_en",
    "venue_ar",
  ],
  defaultSort: {
    field: "start_date",
    direction: "desc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "start_date",
      label: "Start Date",
      type: "date",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "end_date",
      label: "End Date",
      type: "date",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "venue_en",
      label: "Venue (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "venue_ar",
      label: "Venue (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Exhibition",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "28%",
    },
    {
      key: "venue_en",
      label: "Venue",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "20%",
    },
    {
      key: "start_date",
      label: "Start Date",
      fieldType: "date",
      sortable: true,
      width: "16%",
    },
    {
      key: "end_date",
      label: "End Date",
      fieldType: "date",
      sortable: true,
      width: "16%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "20%",
    },
  ],
  table: {
    title: "Exhibitions",
    description: "Read-only Exhibitions CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Exhibition",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "28%",
      },
      {
        key: "venue_en",
        label: "Venue",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "20%",
      },
      {
        key: "start_date",
        label: "Start Date",
        fieldType: "date",
        sortable: true,
        width: "16%",
      },
      {
        key: "end_date",
        label: "End Date",
        fieldType: "date",
        sortable: true,
        width: "16%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "20%",
      },
    ],
    emptyTitle: "No exhibitions available",
    emptyDescription: "Exhibitions will appear here when future CMS data wiring is implemented.",
  },
};