import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Project } from "@/types";

export type ProjectsCrudEntity = Project & Record<string, unknown>;

export const projectsCrudConfig: CrudModuleConfiguration<ProjectsCrudEntity> = {
  moduleKey: "projects",
  moduleLabel: "Projects",
  routePath: "/admin/projects",
  entityLabel: "Project",
  entityLabelPlural: "Projects",
  statusField: "status",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "description_en",
    "description_ar",
    "client_en",
    "client_ar",
    "type",
    "status",
  ],
  defaultSort: {
    field: "year",
    direction: "desc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "client_en",
      label: "Client (English)",
      type: "string",
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "client_ar",
      label: "Client (Arabic)",
      type: "string",
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "type",
      label: "Type",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "year",
      label: "Year",
      type: "number",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "status",
      label: "Status",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Project",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "26%",
    },
    {
      key: "client_en",
      label: "Client",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "18%",
    },
    {
      key: "type",
      label: "Type",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "16%",
    },
    {
      key: "year",
      label: "Year",
      fieldType: "number",
      sortable: true,
      align: "right",
      width: "10%",
    },
    {
      key: "status",
      label: "Status",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "14%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "16%",
    },
  ],
  table: {
    title: "Projects",
    description: "Read-only Projects CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Project",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "26%",
      },
      {
        key: "client_en",
        label: "Client",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "18%",
      },
      {
        key: "type",
        label: "Type",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "16%",
      },
      {
        key: "year",
        label: "Year",
        fieldType: "number",
        sortable: true,
        align: "right",
        width: "10%",
      },
      {
        key: "status",
        label: "Status",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "14%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "16%",
      },
    ],
    emptyTitle: "No projects available",
    emptyDescription: "Projects will appear here when future CMS data wiring is implemented.",
  },
};