import type { TableModuleConfig } from "@/lib/tables";
import { VisibilityStatus, type Artwork } from "@/types";

export type ArtworksTableEntity = Artwork & Record<string, unknown>;

export const artworksTableConfig: TableModuleConfig<ArtworksTableEntity> = {
  entity: "artworks",
  table: {
    key: "artworks-table",
    title: "Artworks",
    description: "Table configuration for the future Artworks CMS listing.",
    columns: [
      {
        key: "title_en",
        label: "Artwork",
        type: "text",
        sortable: true,
        searchable: true,
        width: "22%",
        description: "Primary English artwork title.",
      },
      {
        key: "title_ar",
        label: "Arabic Title",
        type: "text",
        sortable: true,
        searchable: true,
        width: "16%",
      },
      {
        key: "artist_id",
        label: "Artist",
        type: "text",
        sortable: true,
        searchable: true,
        filterable: true,
        width: "14%",
        description: "References a future Artists CMS record.",
      },
      {
        key: "year",
        label: "Year",
        type: "number",
        sortable: true,
        filterable: true,
        align: "right",
        width: "8%",
      },
      {
        key: "availability_status",
        label: "Availability",
        type: "status",
        sortable: true,
        searchable: true,
        filterable: true,
        width: "14%",
        description: "Maps to the available, reserved, sold, on-loan, or not-for-sale workflow state.",
      },
      {
        key: "price_status",
        label: "Price Status",
        type: "status",
        sortable: true,
        searchable: true,
        filterable: true,
        width: "14%",
        description: "Maps to future artwork price display controls.",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        type: "visibility",
        sortable: true,
        filterable: true,
        width: "12%",
        description: "Maps to the public, private, VIP, or hidden visibility status.",
      },
      {
        key: "display_order",
        label: "Order",
        type: "number",
        sortable: true,
        align: "right",
        hidden: true,
      },
      {
        key: "featured",
        label: "Featured",
        type: "boolean",
        sortable: true,
        filterable: true,
        align: "center",
        hidden: true,
      },
      {
        key: "is_featured_homepage",
        label: "Homepage",
        type: "boolean",
        sortable: true,
        filterable: true,
        align: "center",
        hidden: true,
      },
      {
        key: "updated_at",
        label: "Updated",
        type: "datetime",
        sortable: true,
        hidden: true,
      },
    ],
    defaultSort: {
      field: "display_order",
      direction: "asc",
    },
    defaultFilters: [
      {
        field: "visibility_status",
        operator: "notEquals",
        value: VisibilityStatus.Hidden,
      },
    ],
    defaultPagination: {
      page: 1,
      pageSize: 20,
    },
    emptyTitle: "No artworks available",
    emptyDescription: "Artworks will appear when future CMS data access is connected.",
  },
};