import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Artwork } from "@/types";

export type ArtworksCrudEntity = Artwork & Record<string, unknown>;

export const artworksCrudConfig: CrudModuleConfiguration<ArtworksCrudEntity> = {
  moduleKey: "artworks",
  moduleLabel: "Artworks",
  routePath: "/admin/artworks",
  entityLabel: "Artwork",
  entityLabelPlural: "Artworks",
  statusField: "availability_status",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "medium_en",
    "medium_ar",
    "dimensions",
    "availability_status",
    "price_status",
  ],
  defaultSort: {
    field: "display_order",
    direction: "asc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "artist_id",
      label: "Artist",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
      description: "References a future Artists CMS record.",
    },
    {
      key: "collection_id",
      label: "Collection",
      type: "string",
      visibleInTable: false,
      visibleInForm: true,
      description: "References a future Collections CMS record.",
    },
    {
      key: "year",
      label: "Year",
      type: "number",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "medium_en",
      label: "Medium (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "medium_ar",
      label: "Medium (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "dimensions",
      label: "Dimensions",
      type: "string",
      required: true,
      searchable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "price",
      label: "Price",
      type: "number",
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "currency",
      label: "Currency",
      type: "string",
      required: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "price_status",
      label: "Price Status",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "availability_status",
      label: "Availability",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "primary_image_id",
      label: "Primary Image",
      type: "image",
      visibleInTable: false,
      visibleInForm: true,
      description: "References a future CMS media record.",
    },
    {
      key: "featured",
      label: "Featured",
      type: "boolean",
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "is_featured_homepage",
      label: "Homepage Feature",
      type: "boolean",
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "display_order",
      label: "Display Order",
      type: "number",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Artwork",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "24%",
    },
    {
      key: "artist_id",
      label: "Artist",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "16%",
    },
    {
      key: "year",
      label: "Year",
      fieldType: "number",
      sortable: true,
      align: "right",
      width: "8%",
    },
    {
      key: "availability_status",
      label: "Availability",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "16%",
    },
    {
      key: "price_status",
      label: "Price",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "14%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "12%",
    },
    {
      key: "display_order",
      label: "Order",
      fieldType: "number",
      sortable: true,
      align: "right",
      width: "10%",
    },
  ],
  table: {
    title: "Artworks",
    description: "Read-only Artworks CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Artwork",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "24%",
      },
      {
        key: "artist_id",
        label: "Artist",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "16%",
      },
      {
        key: "year",
        label: "Year",
        fieldType: "number",
        sortable: true,
        align: "right",
        width: "8%",
      },
      {
        key: "availability_status",
        label: "Availability",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "16%",
      },
      {
        key: "price_status",
        label: "Price",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "14%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "12%",
      },
      {
        key: "display_order",
        label: "Order",
        fieldType: "number",
        sortable: true,
        align: "right",
        width: "10%",
      },
    ],
    emptyTitle: "No artworks available",
    emptyDescription: "Artworks will appear here when future CMS data wiring is implemented.",
  },
};