import type { CrudModuleConfiguration } from "@/lib/crud";
import type { News } from "@/types";

export type NewsCrudEntity = News & Record<string, unknown>;

export const newsCrudConfig: CrudModuleConfiguration<NewsCrudEntity> = {
  moduleKey: "news",
  moduleLabel: "News",
  routePath: "/admin/news",
  entityLabel: "News Item",
  entityLabelPlural: "News",
  statusField: "category",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "content_en",
    "content_ar",
    "excerpt_en",
    "excerpt_ar",
    "category",
  ],
  defaultSort: {
    field: "publish_date",
    direction: "desc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "excerpt_en",
      label: "Excerpt (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "excerpt_ar",
      label: "Excerpt (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "content_en",
      label: "Content (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "content_ar",
      label: "Content (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "category",
      label: "Category",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "publish_date",
      label: "Publish Date",
      type: "date",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "image_id",
      label: "Image",
      type: "image",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "News Item",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "28%",
    },
    {
      key: "category",
      label: "Category",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "18%",
    },
    {
      key: "publish_date",
      label: "Publish Date",
      fieldType: "date",
      sortable: true,
      width: "18%",
    },
    {
      key: "excerpt_en",
      label: "Excerpt",
      fieldType: "text",
      searchable: true,
      width: "20%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "16%",
    },
  ],
  table: {
    title: "News",
    description: "Read-only News CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "News Item",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "28%",
      },
      {
        key: "category",
        label: "Category",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "18%",
      },
      {
        key: "publish_date",
        label: "Publish Date",
        fieldType: "date",
        sortable: true,
        width: "18%",
      },
      {
        key: "excerpt_en",
        label: "Excerpt",
        fieldType: "text",
        searchable: true,
        width: "20%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "16%",
      },
    ],
    emptyTitle: "No news available",
    emptyDescription: "News items will appear here when future CMS data wiring is implemented.",
  },
};