import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Collection } from "@/types";

export type CollectionsCrudEntity = Collection & Record<string, unknown>;

export const collectionsCrudConfig: CrudModuleConfiguration<CollectionsCrudEntity> = {
  moduleKey: "collections",
  moduleLabel: "Collections",
  routePath: "/admin/collections",
  entityLabel: "Collection",
  entityLabelPlural: "Collections",
  visibilityField: "visibility_status",
  searchFields: ["title_en", "title_ar", "description_en", "description_ar"],
  defaultSort: {
    field: "title_en",
    direction: "asc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Collection",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "32%",
    },
    {
      key: "title_ar",
      label: "Arabic Title",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "28%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "18%",
    },
    {
      key: "updated_at",
      label: "Updated",
      fieldType: "datetime",
      sortable: true,
      width: "22%",
    },
  ],
  table: {
    title: "Collections",
    description: "Read-only Collections CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Collection",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "32%",
      },
      {
        key: "title_ar",
        label: "Arabic Title",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "28%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "18%",
      },
      {
        key: "updated_at",
        label: "Updated",
        fieldType: "datetime",
        sortable: true,
        width: "22%",
      },
    ],
    emptyTitle: "No collections available",
    emptyDescription: "Collections will appear here when future CMS data wiring is implemented.",
  },
};