export enum VisibilityStatus { Public = 'public', Private = 'private', Vip = 'vip', Hidden = 'hidden' }
export enum AvailabilityStatus { Available = 'available', Reserved = 'reserved', Sold = 'sold', OnLoan = 'on_loan', NotForSale = 'not_for_sale' }
export enum PriceStatus { PriceVisible = 'price_visible', PriceUponRequest = 'price_upon_request', PrivateQuote = 'private_quote' }
export enum CertificateStatus { Draft = 'draft', Issued = 'issued', Revoked = 'revoked', Reissued = 'reissued' }
export enum AppointmentType { GalleryVisit = 'gallery_visit', PrivateViewing = 'private_viewing', ArtistMeeting = 'artist_meeting', Consultation = 'consultation', CollectionReview = 'collection_review' }
export enum InquiryType { ArtworkAcquisition = 'artwork_acquisition', ArtistInquiry = 'artist_inquiry', ServiceInquiry = 'service_inquiry', ProjectInquiry = 'project_inquiry', General = 'general' }
export interface Settings { site_name_en:string; site_name_ar:string; description_en:string; description_ar:string; contact_email:string; contact_phone:string; address_en:string; address_ar:string; social_media:{instagram?:string;twitter?:string;facebook?:string}; }
export interface Artist { id:string; slug:string; name_en:string; name_ar:string; bio_en:string; bio_ar:string; birth_year:number; nationality_en:string; nationality_ar:string; website?:string; email?:string; instagram?:string; profile_image_id?:string; featured:boolean; display_order:number; representation_status:string; visibility_status:VisibilityStatus; created_at:string; updated_at:string; }
export interface Artwork { id:string; slug:string; title_en:string; title_ar:string; artist_id:string; collection_id?:string|null; year:number; medium_en:string; medium_ar:string; dimensions:string; description_en:string; description_ar:string; price?:number|null; currency:string; price_status:PriceStatus; availability_status:AvailabilityStatus; visibility_status:VisibilityStatus; primary_image_id?:string; featured:boolean; display_order:number; is_featured_homepage:boolean; created_at:string; updated_at:string; }
export interface Collection { id:string; slug:string; title_en:string; title_ar:string; description_en:string; description_ar:string; cover_media_id?:string|null; visibility_status:VisibilityStatus; created_at:string; updated_at:string; }
export interface Exhibition { id:string; slug:string; title_en:string; title_ar:string; description_en:string; description_ar:string; start_date:string; end_date:string; venue_en:string; venue_ar:string; cover_media_id?:string|null; visibility_status:VisibilityStatus; created_at:string; updated_at:string; }
export interface Project { id:string; slug:string; title_en:string; title_ar:string; description_en:string; description_ar:string; client_en?:string; client_ar?:string; type:string; year:number; status:string; cover_media_id?:string|null; visibility_status:VisibilityStatus; created_at:string; updated_at:string; }
export interface Service { id:string; slug:string; title_en:string; title_ar:string; description_en:string; description_ar:string; features_en:string[]; features_ar:string[]; price_info?:Record<string, any>; cover_media_id?:string|null; visibility_status:VisibilityStatus; created_at:string; updated_at:string; }
export interface News { id:string; slug:string; title_en:string; title_ar:string; content_en:string; content_ar:string; excerpt_en:string; excerpt_ar:string; category:string; publish_date:string; image_id?:string|null; visibility_status:VisibilityStatus; }
export interface Publication { id:string; slug:string; title_en:string; title_ar:string; description_en:string; description_ar:string; type:string; file_url:string; cover_image_id?:string|null; publish_date:string; visibility_status:VisibilityStatus; }
export interface Media { id:string; url:string; alt_en:string; alt_ar:string; type:string; mime_type:string; width?:number; height?:number; file_size:number; checksum:string; dominant_color?:string; copyright:string; photographer?:string; license:string; created_by?:string; updated_at:string; storage_provider:string; storage_path:string; created_at:string; }
export interface ArtworkImage { id:string; artwork_id:string; media_id:string; is_primary:boolean; sort_order:number; caption_en:string; caption_ar:string; created_at:string; }
export interface ArtworkFile { id:string; artwork_id:string; media_id:string; file_type:string; title_en:string; title_ar:string; created_at:string; }
export interface ArtworkHistory { id:string; artwork_id:string; action:string; old_value:string; new_value:string; changed_by:string; changed_at:string; note?:string; }
export interface ExhibitionArtist { id:string; exhibition_id:string; artist_id:string; role:string; added_at:string; }
export interface ExhibitionArtwork { id:string; exhibition_id:string; artwork_id:string; display_order:number; added_at:string; }
export interface Participation { id:string; artist_id:string; title_en:string; title_ar:string; type:string; date:string; location_en:string; location_ar:string; description_en:string; description_ar:string; status:string; visibility_status:VisibilityStatus; }
export interface ProjectArtist { id:string; project_id:string; artist_id:string; role:string; added_at:string; }
export interface ProjectArtwork { id:string; project_id:string; artwork_id:string; inclusion_note?:string; added_at:string; }
export interface Certificate { id:string; certificate_number:string; artwork_id:string; issued_date:string; template_id:string; qr_code:string; verification_url:string; status:CertificateStatus; issued_by:string; approved_by:string; issued_version:number; issued_at:string; last_updated:string; }
export interface CertificateTemplate { id:string; name_en:string; name_ar:string; layout:string; label_schema:Record<string,{en:string;ar:string}>; created_at:string; }
export interface Inquiry { id:string; type:InquiryType; name:string; email:string; phone?:string; artwork_id?:string|null; artist_id?:string|null; service_id?:string|null; project_id?:string|null; message_en?:string; message_ar?:string; status:string; created_at:string; }
export interface Appointment { id:string; name:string; email:string; phone?:string; preferred_date:string; preferred_time:string; appointment_type:AppointmentType; artist_id?:string|null; artwork_id?:string|null; service_id?:string|null; message_en?:string; message_ar?:string; status:string; created_at:string; }
export interface NewsletterSubscriber { id:string; email:string; preferences:Record<string, boolean>; verified:boolean; subscribed_at:string; }
export interface AIKnowledge { id:string; source_type:string; source_id:string; allowed_for_ai:boolean; embedding_status:string; last_indexed?:string|null; language:string; }
export interface AILog { id:string; session_id:string; query_en?:string; query_ar?:string; response_en?:string; response_ar?:string; confidence:number; created_at:string; }
export interface AuditLog { id:string; entity:string; entity_id:string; action:string; old_value?:string|null; new_value?:string|null; performed_by:string; timestamp:string; ip_address:string; }
