import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Service } from "@/types";

export type ServicesCrudEntity = Service & Record<string, unknown>;

export const servicesCrudConfig: CrudModuleConfiguration<ServicesCrudEntity> = {
  moduleKey: "services",
  moduleLabel: "Services",
  routePath: "/admin/services",
  entityLabel: "Service",
  entityLabelPlural: "Services",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "description_en",
    "description_ar",
    "features_en",
    "features_ar",
  ],
  defaultSort: {
    field: "title_en",
    direction: "asc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "features_en",
      label: "Features (English)",
      type: "json",
      required: true,
      searchable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "features_ar",
      label: "Features (Arabic)",
      type: "json",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "price_info",
      label: "Price Info",
      type: "json",
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Service",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "30%",
    },
    {
      key: "features_en",
      label: "Features",
      fieldType: "json",
      searchable: true,
      width: "30%",
    },
    {
      key: "price_info",
      label: "Price Info",
      fieldType: "json",
      width: "20%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "20%",
    },
  ],
  table: {
    title: "Services",
    description: "Read-only Services CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Service",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "30%",
      },
      {
        key: "features_en",
        label: "Features",
        fieldType: "json",
        searchable: true,
        width: "30%",
      },
      {
        key: "price_info",
        label: "Price Info",
        fieldType: "json",
        width: "20%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "20%",
      },
    ],
    emptyTitle: "No services available",
    emptyDescription: "Services will appear here when future CMS data wiring is implemented.",
  },
};