import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Publication } from "@/types";

export type PublicationsCrudEntity = Publication & Record<string, unknown>;

export const publicationsCrudConfig: CrudModuleConfiguration<PublicationsCrudEntity> = {
  moduleKey: "publications",
  moduleLabel: "Publications",
  routePath: "/admin/publications",
  entityLabel: "Publication",
  entityLabelPlural: "Publications",
  statusField: "type",
  visibilityField: "visibility_status",
  searchFields: [
    "title_en",
    "title_ar",
    "description_en",
    "description_ar",
    "type",
    "file_url",
  ],
  defaultSort: {
    field: "publish_date",
    direction: "desc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "title_en",
      label: "Title (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "title_ar",
      label: "Title (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_en",
      label: "Description (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "description_ar",
      label: "Description (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "type",
      label: "Type",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "file_url",
      label: "File URL",
      type: "url",
      required: true,
      searchable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "cover_image_id",
      label: "Cover Image",
      type: "image",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "publish_date",
      label: "Publish Date",
      type: "date",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
  ],
  columns: [
    {
      key: "title_en",
      label: "Publication",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "28%",
    },
    {
      key: "type",
      label: "Type",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "16%",
    },
    {
      key: "file_url",
      label: "File URL",
      fieldType: "url",
      searchable: true,
      width: "22%",
    },
    {
      key: "publish_date",
      label: "Publish Date",
      fieldType: "date",
      sortable: true,
      width: "18%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "16%",
    },
  ],
  table: {
    title: "Publications",
    description: "Read-only Publications CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "title_en",
        label: "Publication",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "28%",
      },
      {
        key: "type",
        label: "Type",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "16%",
      },
      {
        key: "file_url",
        label: "File URL",
        fieldType: "url",
        searchable: true,
        width: "22%",
      },
      {
        key: "publish_date",
        label: "Publish Date",
        fieldType: "date",
        sortable: true,
        width: "18%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "16%",
      },
    ],
    emptyTitle: "No publications available",
    emptyDescription: "Publications will appear here when future CMS data wiring is implemented.",
  },
};