import type { CrudModuleConfiguration } from "@/lib/crud";
import type { Artist } from "@/types";

export type ArtistsCrudEntity = Artist & Record<string, unknown>;

export const artistsCrudConfig: CrudModuleConfiguration<ArtistsCrudEntity> = {
  moduleKey: "artists",
  moduleLabel: "Artists",
  routePath: "/admin/artists",
  entityLabel: "Artist",
  entityLabelPlural: "Artists",
  statusField: "representation_status",
  visibilityField: "visibility_status",
  searchFields: ["name_en", "name_ar", "nationality_en", "nationality_ar", "representation_status"],
  defaultSort: {
    field: "display_order",
    direction: "asc",
  },
  fields: [
    {
      key: "id",
      label: "ID",
      type: "string",
      required: true,
      readonly: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "slug",
      label: "Slug",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "name_en",
      label: "Name (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "name_ar",
      label: "Name (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "bio_en",
      label: "Biography (English)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "bio_ar",
      label: "Biography (Arabic)",
      type: "text",
      required: true,
      searchable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "birth_year",
      label: "Birth Year",
      type: "number",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "nationality_en",
      label: "Nationality (English)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "nationality_ar",
      label: "Nationality (Arabic)",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "website",
      label: "Website",
      type: "url",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "email",
      label: "Email",
      type: "string",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "instagram",
      label: "Instagram",
      type: "string",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "profile_image_id",
      label: "Profile Image",
      type: "image",
      visibleInTable: false,
      visibleInForm: true,
    },
    {
      key: "featured",
      label: "Featured",
      type: "boolean",
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "display_order",
      label: "Display Order",
      type: "number",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "representation_status",
      label: "Representation Status",
      type: "status",
      required: true,
      searchable: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "visibility_status",
      label: "Visibility",
      type: "visibility",
      required: true,
      sortable: true,
      visibleInTable: true,
      visibleInForm: true,
    },
    {
      key: "created_at",
      label: "Created",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
    {
      key: "updated_at",
      label: "Updated",
      type: "datetime",
      readonly: true,
      sortable: true,
      visibleInTable: false,
      visibleInForm: false,
    },
  ],
  columns: [
    {
      key: "name_en",
      label: "Artist",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "28%",
    },
    {
      key: "nationality_en",
      label: "Nationality",
      fieldType: "string",
      sortable: true,
      searchable: true,
      width: "18%",
    },
    {
      key: "representation_status",
      label: "Status",
      fieldType: "status",
      sortable: true,
      searchable: true,
      width: "18%",
    },
    {
      key: "visibility_status",
      label: "Visibility",
      fieldType: "visibility",
      sortable: true,
      width: "16%",
    },
    {
      key: "display_order",
      label: "Order",
      fieldType: "number",
      sortable: true,
      align: "right",
      width: "10%",
    },
    {
      key: "featured",
      label: "Featured",
      fieldType: "boolean",
      sortable: true,
      align: "center",
      width: "10%",
    },
  ],
  table: {
    title: "Artists",
    description: "Read-only Artists CMS configuration prepared for future create, edit, and delete workflows.",
    columns: [
      {
        key: "name_en",
        label: "Artist",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "28%",
      },
      {
        key: "nationality_en",
        label: "Nationality",
        fieldType: "string",
        sortable: true,
        searchable: true,
        width: "18%",
      },
      {
        key: "representation_status",
        label: "Status",
        fieldType: "status",
        sortable: true,
        searchable: true,
        width: "18%",
      },
      {
        key: "visibility_status",
        label: "Visibility",
        fieldType: "visibility",
        sortable: true,
        width: "16%",
      },
      {
        key: "display_order",
        label: "Order",
        fieldType: "number",
        sortable: true,
        align: "right",
        width: "10%",
      },
      {
        key: "featured",
        label: "Featured",
        fieldType: "boolean",
        sortable: true,
        align: "center",
        width: "10%",
      },
    ],
    emptyTitle: "No artists available",
    emptyDescription: "Artists will appear here when future CMS data wiring is implemented.",
  },
};